import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/ui";
import { Locales } from "@/dictionaries";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ lang: Locales }>;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        
      </head>
      <body>
        <Header />
        <main className="bg-neutral-900 p-16 flex min-h-screen  align-middle justify-center">
          {children}
        </main>
        <footer></footer>
      </body>
    </html>
  );
}
